#pragma once

#include "sound_headers/double_beep.h"
#include "sound_headers/double_beep_125.h"
#include "sound_headers/time_beep_high.h"
#include "sound_headers/strike.h"
#include "sound_headers/bomb_defused.h"
#include "sound_headers/explosion.h"
#include "sound_headers/game_over_fanfare.h"
#include "sound_headers/alarm_clock_beep.h"
#include "sound_headers/alarm_clock_snooze.h"
#include "sound_headers/alarm_emergency.h"
#include "sound_headers/simon_red.h"
#include "sound_headers/simon_blue.h"
#include "sound_headers/simon_green.h"
#include "sound_headers/simon_yellow.h"