[platformio]
build_dir = ../build/audio
default_envs = audio

[env]
framework = arduino
monitor_speed = 115200
monitor_port = COM8
upload_protocol = cmsis-dap
upload_port = COM8
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
board_build.core = earlephilhower
build_flags = -DEDGE_AUDIO -DPIO_FRAMEWORK_ARDUINO_ENABLE_BLUETOOTH
	
lib_deps = 
	coryjfowler/mcp_can@^1.5.1
	https://github.com/pschatzmann/arduino-audio-tools.git
	https://github.com/adafruit/Adafruit_TLV320_I2S.git
lib_extra_dirs = ../shared_libs

[env:audio]
debug_tool = cmsis-dap
build_type = debug
debug_build_flags = -O0 -ggdb3 -g3