[env:can_test_receive]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino
board_build.core = earlephilhower
build_flags = -DMODULE_DEBUG
lib_deps = 
	coryjfowler/mcp_can@^1.5.1
lib_extra_dirs = ../shared_libs

[platformio]
build_dir = ..\build\can_test_receive

