[platformio]
build_dir = ..\build\simon_says
default_envs = 

[env]
framework = arduino
monitor_speed = 115200
monitor_port = COM8
upload_protocol = cmsis-dap
upload_port = COM8
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
board_build.core = earlephilhower
build_flags = -DEDGE_SERIAL_NUMBER
lib_deps = 
	coryjfowler/mcp_can@^1.5.1
lib_extra_dirs = 
    ../shared_libs

[env:simon_says]
debug_tool = cmsis-dap
build_type = debug
debug_build_flags = -O0 -ggdb3 -g3